### ISSUE TITLE
Randomize unicode characters when registering email

### ISSUE THREAD

**Issue by XCanG** [moustacheminer/discordmail#10]
My nick have wide set of characters which is similar to letters, but anyway it unicode and my mail generated as `============#5512@discordmail.com` which look pretty bad and I think you need use some random function with a-z, 0-9 character set when you create mail address.

Also look at this collection: https://pastebin.com/2M8ZZhi0 this is similar to latin letters, but all is unicode.

**Comment by 7coil** [comment]
RFC 6531 allows UTF-8 characters in emails above `U+007F`, which could come into handy.

**Comment by 7coil** [comment]
https://tools.ietf.org/html/rfc6531

**Comment by 7coil** [comment]
A new regex has been written to convert Discord usernames to a RFC-6531 compatible email.

```
/[^\w\d!#$&'*+\-/=?^_`{|}~\u007F-\uFFFF]+/g
```
