### ISSUE TITLE
Add account on discordmail site...

### ISSUE THREAD

**Issue by XCanG** [moustacheminer/discordmail#12]
Many bots have ability to use OAuth2, so you can login on site using your discord account, as an example: https://www.tatsumaki.xyz/ (Dashboard button), or https://www.dynobot.net/

Will be good if I can open site, login with my Discord account and see all emails I have and ability to open it (without need to read DM in Discord and open link by bot) because of links what unpossible to remind.

Official OAuth2 documentation you can find here: https://discordapp.com/developers/docs/topics/oauth2

**Comment by 7coil** [comment]
You can now view emails at https://discordmail.com/mail after authenticating
