### ISSUE TITLE
HTML Email support

### ISSUE THREAD

**Issue by aveao** [moustacheminer/discordmail#2]
![](https://s.ave.zone/732f.png)

HTML-only emails appear as "Empty E-mail".

Support for them would be neato.

**Comment by 7coil** [comment]
Wew, so many things going on now

The text is parsed by mailguns, which automatically interprets the email for it's content. This will require our own parser, which may be less advanced compared to what mailgun currently provides.

I will try and find parsers / better options in mailgun to solve this... Soon™

**Comment by aveao** [comment]
Maybe it can attach the .html to the message? Or allows us to request it with a command?

**Comment by 7coil** [comment]
Hosting the email on discordmail.com will cost £35 due to the need to store emails, which is required for registering in accordance to the data protection act in the UK.

Sending the HTML off as a file might work, but would require the user to save a file to their hard drive, something that may throw off users.

Talking about the data protection act, I may technically be in breach of the act due to transporting potentially personal data outside the EU. This is, however a question for another time.

**Comment by aveao** [comment]
> Sending the HTML off as a file might work, but would require the user to save a file to their hard drive, something that may throw off users.

Can't you just keep the parsed text and add the html file as an attachment? [Or just make it a command, as I said?]

**Comment by 7coil** [comment]
My original idea was to attach the HTML file. However...

This would require multiple messages due to not being able to add more than 1 attachment (in case someone attaches something to their email)

Also, requesting with a command requires me to store the email. Data protection etc

**Comment by aveao** [comment]
> This would require multiple messages due to not being able to add more than 1 attachment (in case someone attaches something to their email)

Honestly that doesn't sound so bad.

Maybe I'm overcomplicating but... maybe some config setting to flip that on or off? >_>

Also, what currently happens when user attaches more than one attachment to a file?

**Comment by 7coil** [comment]
Attaches one, and sends a notification to the sender that only 1 attachment is supported

**Comment by 7coil** [comment]
I have decided to go the route of storing personal information.

As Moustacheminer Server Services operates within the UK, I have underwent an investigation to determine if Discord is an adequate data holder to transfer data outside the EEA (European Economic Area).

This file is found in the latest commit, underlining the security features that Discord has, which should allow me to legally transfer the data from MSS to Discord.

Currently, DiscordMail is in a limbo state of legality, so registering under the Data Protection Act will help anyway.

**Comment by 7coil** [comment]
This feature has been added to DiscordMail, but has not been deployed yet.

https://send-me-some.discordmail.com/1503174469.png
https://send-me-some.discordmail.com/1503174494.png

**Comment by 7coil** [comment]
_If you're reading at a later date, it has been implemented_
