### ISSUE TITLE
Convert Discord markdown into HTML and send HTML mails

### ISSUE THREAD

**Issue by XCanG** [moustacheminer/discordmail#8]
Currently dmail bot have several issues:
1) Any text, i.e. **bold**, _italic_, combined, e.t.c... writed in command will send as raw text in a mail. At same time HTML like `<b>bold</b>`, `<strong>bold</strong>`, `<i>italic</i>` e.t.c. send as plain text. Need detect that and replace markdown into HTML tags and HTML raw tags send as HTML, not plain text.

Don't check if bot can send images, but you may know if it possible.

2) Any **mentions** sended as raw text: http://hnng.moe/f/TZ8 (image from mailbox) - need replace that to text. If it mention user, then name of a user, if it channel, then channel name, if it role, then role name. I think it also possible to format by HTML tags and may be make looks like discord mention (what on white theme).
https://abal.moe/Eris/docs/Message `message.mentions` / `.channelMentions` / `.roleMentions`

**Comment by 7coil** [comment]
Currently, emails received are parsed into plain text by mailgun, and emails sent are sent as plaintext only. 

Plan:
1.a. Messages received should be scraped to markdown
1.b. Messages sent should be interpreted as markdown and converted to HTML

2. replace special discord notation before sending

**Comment by XCanG** [comment]
Just small notation, in Discord embed you can use markdown `[text](url)` (in regular message this markdown not parsed).

**Comment by 7coil** [comment]
Added in latest commit

- Emails are converted to Markdown
- .cleanContent is used instead of content

**Comment by XCanG** [comment]
Hm, I send a test email from my mail program to dmail
This is how it should look as it was a mail:
![default](https://user-images.githubusercontent.com/4011523/30775783-05d91a1e-a0b4-11e7-804a-22d5736d29aa.png)

This is what I recieve in DM in Discord:
![default](https://user-images.githubusercontent.com/4011523/30775780-fa8f4e76-a0b3-11e7-973e-c440e6e39431.png)

Problem what it:
1) Add extra spaces in HTML tags place (before and after)
2) Don't convert it back in markdown _(I remind about `[text](url)` when you send embed in discord, it possible to paste)_

**Comment by 7coil** [comment]
![](https://mss.ovh/1506190795.png)

**Comment by XCanG** [comment]
Another test from Discord to email also have small problem
Discord: 
![default](https://user-images.githubusercontent.com/4011523/30775839-3b66739c-a0b5-11e7-95fd-0dba28cdd717.png)
Email:
![default](https://user-images.githubusercontent.com/4011523/30775840-42a95a3e-a0b5-11e7-8e10-c6296715dcbe.png)

1) "Multiplier" word have 2 html tags `<strong>`, it boldered than bolder.
2) Single newline don't counted as newline (no `<br />` or new `<p>` tag).

**Comment by 7coil** [comment]
Discord Embeds **ARE NOT** HTML

Anything you get from DiscordMail is the same as what you put in to DiscordMail

**Comment by 7coil** [comment]
oh wait

**Comment by 7coil** [comment]
You had me confused, you should have screenshotted the entire window

![](https://mss.ovh/1506190947.png)

**Comment by XCanG** [comment]
Oh... About your screenshot links also have extra space.
```
You had me confused, you should have screenshotted the entire window
```
What is it you mention? Email to dmail or dmail to email?

----------
The difference between single Enter and two is single make `<br />` in HTML, but two close `<p>` tag and open new. On your screenshot it ignore `<br />` tag.

**Comment by 7coil** [comment]
![](https://mss.ovh/1506191446.png)
